### DISCUSSION TITLE
[Question] Passive joint and action space size (skrl)

### DISCUSSION THREAD

**Discussion by AndreaRossetto** [isaac-sim/IsaacLab#2272] [Q&A]
### Question

Hi, 
I've created a custom robot (kind of cassie robot) with some passive joints, in total I have 12 joints but only 10 are "useful" in the action state (the controllable joints and readable joint position are only 10). If in the DirectRLEnvCfg I set the action_space to 10 I get the error the inputs of the tensor is not matching

```
class RobotEnvCfg(DirectRLEnvCfg):
    # env
    decimation = 4                  # Number of time steps between actions
    episode_length_s = 20.0         # Episode time max in seconds
    action_scale = 0.5 
    action_space = 12               # Number of actions the neural net returns
    observation_space = 53 
    state_space = 0 
```
skrl yaml model:
```
models:
  separate: True
  policy:  # see gaussian_model parameters
    class: GaussianMixin
    clip_actions: False
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.0
    network:
      - name: net
        input: STATES
        layers:
          - linear: [512]
          - linear: [256]
          - linear: [256]
        activations: ["relu", "relu", "relu"]
    output: ACTIONS
  value:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers:
          - linear: [512]
          - linear: [256]
          - linear: [256]
        activations: ["relu", "relu", "relu"]
    output: ONE
```

I wanna remove the two passive rod joints from the action_space, so the actor net output control only the main joins and not the rod joint. How can I do that?
