### ISSUE TITLE
[Bug Report] RGB Image Not Correct When Setting Clip Values Smaller than 0.1

### ISSUE THREAD

**Issue by hzxie** [isaac-sim/IsaacLab#2236]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

### Describe the bug

Here's the image when setting camera clip values equal to 0.1.

![Image](https://github.com/user-attachments/assets/e7bfa152-eba2-4b73-938b-4dfcafb09218)

When changing this value to 0.05, the image becomes very strange.

![Image](https://github.com/user-attachments/assets/c248245e-00e6-4d02-b051-359d5c9f589c)

### Steps to reproduce

Create a camera with the following config:

```python
  cam_cfg = CameraCfg(
    ...
    spawn=sim_utils.PinholeCameraCfg(
        focal_length=2.3,
        focus_distance=400,
        horizontal_aperture=4.6,
        clipping_range=(0.01, 10000),
    ),
    ...
  )
```

The full camera config is shown below

```yaml
camera:
  width: 640
  height: 480
  fps: 15
  focal_length: 2.3
  focus_distance: 400
  horizontal_aperture: 4.6
  clip:
    near: 0.05
    far: 1000
  data_types:
    - rgb
    - distance_to_image_plane
```

### System Info

Describe the characteristic of your environment:

- Commit: f8cf6bad7
- Isaac Sim Version: 4.5.0-rc.36+release.19112.f59b3005.gl
- OS: Windows 11
- GPU: RTX 2080 Ti
- CUDA: 11.7.64
- GPU Driver: 566.24

### Additional context

N/A

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

### Acceptance Criteria

Add the criteria for which this task is considered **done**. If not known at issue creation time, you can add this once the issue is assigned.

- [ ] Criteria 1
- [ ] Criteria 2
