### ISSUE TITLE
[Question] Observation and SKRL setup for Camera and Robot in Manager-based Projects

### ISSUE THREAD

**Issue by cowcnovo** [isaac-sim/IsaacLab#2613]
### Question

I am developing a project to train a robot arm to lift an object based on camera input (both rgb and depth). I have seen that there are many examples using the direct-workflow for incorporating camera observations into the DRL network architecture, especially in SKRL. How can I accomplish this with manager-based workflow? For instance, here is my observation configuration setup:

```
@configclass
class ObservationsCfg:

    @configclass
    class PolicyCfg(ObsGroup):

        # observation terms (order preserved)
        joint_pos = ObsTerm(
            func=mdp.joint_pos_rel,
            params={
                "asset_cfg": SceneEntityCfg("ur5e", joint_names=arm_joint_names+gripper_joint_names),
            }
        )
        joint_vel = ObsTerm(
            func=mdp.joint_vel_rel,
            params={
                "asset_cfg": SceneEntityCfg("ur5e", joint_names=arm_joint_names+gripper_joint_names),
            }
        )
        pose_command = ObsTerm(func=mdp.generated_commands, params={"command_name": "ee_orientation"})
        
        rgb_data = ObsTerm(func=rgb_camera_data)
        depth_data = ObsTerm(func=depth_camera_data)

        actions = ObsTerm(func=mdp.last_action)

        def __post_init__(self):
            self.enable_corruption = True
            self.concatenate_terms = True

    # observation groups
    policy: PolicyCfg = PolicyCfg()
```

And, here is part of the SKRL yaml that I am showing which I would like to use (taken from cartpole_camera skrl_tuple_multidiscrete_ppo_cfg.yaml):

```
seed: 42


# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
#
#             obs[0]                  obs[1]
#               │                       │
#    ┏━━━━━━━━━━▼━━━━━━━━━━┓    ┏━━━━━━━▼━━━━━━━━┓
#    ┃ features_extractor  ┃    ┃ proprioception ┃
#    ┡━━━━━━━━━━━━━━━━━━━━━┩    ┡━━━━━━━━━━━━━━━━┩
#    │ conv2d(32, 8, 4)    │    │ linear(16)     │
#    │ relu                │    │ elu            │
#    │ conv2d(64, 4, 2)    │    │ linear(8)      │
#    │ relu                │    │ elu            │
#    │ conv2d(64, 3, 1)    │    └───────┬────────┘
#    │ relu                │            │
#    │ flatten             │            │
#    │ linear(512)         │            │
#    │ tanh                │            │
#    │ linear(16)          │            │
#    │ tanh                │            │
#    └──────────┬──────────┘            |
#               │                       │
#               └─▶(concatenate)◀───────┘
#                        │
#                 ┏━━━━━━▼━━━━━┓
#                 ┃     net    ┃
#                 ┡━━━━━━━━━━━━┩
#                 │ linear(32) │
#                 │ elu        │
#                 │ linear(32) │
#                 │ elu        │
#                 └──────┬─────┘
# shared                 │
# .......................│.......................
# non-shared             │
#            ┏━━━━━━━━━━━▼━━━━━━━━━━━┓
#            ┃  policy|value output  ┃
#            ┡━━━━━━━━━━━━━━━━━━━━━━━┩
#            │ linear(num_actions|1) │
#            └───────────┬───────────┘
#                        ▼
models:
  separate: False
  policy:  # see multicategorical_model parameters
    class: MultiCategoricalMixin
    unnormalized_log_prob: True
    network:
      - name: features_extractor
        input: permute(OBSERVATIONS[0], (0, 3, 1, 2))  # PyTorch NHWC -> NCHW. Warning: don't permute for JAX since it expects NHWC
        layers:
          - conv2d: {out_channels: 32, kernel_size: 8, stride: 4, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 4, stride: 2, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 3, stride: 1, padding: 0}
          - flatten
          - linear: 512
          - linear: 16
        activations: [relu, relu, relu, null, tanh, tanh]
      - name: proprioception
        input: OBSERVATIONS[1]
        layers: [16, 8]
        activations: elu
      - name: net
        input: concatenate([features_extractor, proprioception])
        layers: [32, 32]
        activations: elu
    output: ACTIONS
  value:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: features_extractor
        input: permute(OBSERVATIONS[0], (0, 3, 1, 2))  # PyTorch NHWC -> NCHW. Warning: don't permute for JAX since it expects NHWC
        layers:
          - conv2d: {out_channels: 32, kernel_size: 8, stride: 4, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 4, stride: 2, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 3, stride: 1, padding: 0}
          - flatten
          - linear: 512
          - linear: 16
        activations: [relu, relu, relu, null, tanh, tanh]
      - name: proprioception
        input: OBSERVATIONS[1]
        layers: [16, 8]
        activations: elu
      - name: net
        input: concatenate([features_extractor, proprioception])
        layers: [32, 32]
        activations: elu
    output: ONE
```

Specifically, how can I modify the input fields and the `OBSERVATIONS` tag to adjust to my policy group observations and seperate the images from the other observation states for the network?

**Comment by Toni-SM** [comment]
Hi @cowcnovo 

As show on the *Note* in docs ([Spaces showcase](https://isaac-sim.github.io/IsaacLab/main/source/overview/environments.html#spaces-showcase)), only the Isaac Lab’s **Direct workflow** supports the definition of observation and action spaces other than `Box`. Currently, it is not possible to use the Manager-based workflow to comply with the [Gymnasium Space](https://gymnasium.farama.org/api/spaces/) standard to specify valid composite observations.

**Comment by hritik-roy-chowdhury** [comment]
Hi @Toni-SM,
Thank you for your response. While the Direct workflow is the supported approach, is it not possible to specify the observations like shown in the yaml file below:

```
models:
  separate: False
  policy:  # Use GaussianMixin for continuous actions
    class: GaussianMixin
    unnormalized_log_prob: True
    network:
      - name: camera_features
        input: permute(OBSERVATIONS["camera_data"], (0, 3, 1, 2))  
        layers:
          - conv2d: {out_channels: 32, kernel_size: 8, stride: 4, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 4, stride: 2, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 3, stride: 1, padding: 0}
          - flatten
          - linear: 512
          - linear: 16
        activations: [relu, relu, relu, null, tanh, tanh]
      - name: proprioception
        input: concatenate([OBSERVATIONS["joint_pos"], OBSERVATIONS["joint_vel"], OBSERVATIONS["pose_command"], OBSERVATIONS["actions"]])
        layers: [64, 64]
        activations: elu
      - name: net
        input: concatenate([camera_features, proprioception])  # Combine features
        layers: [32, 32]
        activations: elu
    output: ACTIONS
```

I actually trained the agent and there are no errors or warnings associated to observation spaces. In fact, I can see that the robot is being trained and it is approaching the object based on the camera observations. I just want to confirm whether this the YAML file shown here is configured in a correct way to solve this problem, and if still going with this manager-based approach will lead to any problems with the training itself.
